<html xmlns:string="xalan://java.lang.String" xmlns:lxslt="http://xml.apache.org/xslt">
<head>
<META http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Unit Test Results: All Errors</title>
<link rel="stylesheet" type="text/css" title="Style" href="stylesheet.css">
</head>
<body onload="open('allclasses-frame.html','classListFrame')">
<h1>Unit Test Results.</h1>
<table width="100%">
<tr>
<td align="left"></td><td align="right">Designed for use with <a href="http://www.junit.org/">JUnit</a> and <a href="http://ant.apache.org/">Ant</a>.</td>
</tr>
</table>
<hr size="1">
<h2>All Errors</h2>
<table class="details" border="0" cellpadding="5" cellspacing="2" width="95%">
<tr valign="top">
<th>Class</th><th>Name</th><th>Status</th><th width="80%">Type</th><th nowrap>Time(s)</th>
</tr>
<tr valign="top" class="Error">
<td><a href="doc/books/systems/pn/test/junit/13_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[4] /home/travis/build/icyphy/ptII/doc/books/systems/pn/test/auto/ResourcePool.xml (RunModel)"></a><a href="doc/books/systems/pn/test/junit/13_JUnitTclTest.html#[4] /home/travis/build/icyphy/ptII/doc/books/systems/pn/test/auto/ResourcePool.xml (RunModel)">[4] /home/travis/build/icyphy/ptII/doc/books/systems/pn/test/auto/ResourcePool.xml (RunModel)</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.reflect.InvocationTargetException<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Test fails in iteration 0.<br>Value was: 24. Should have been: 1<br>  in .ResourcePool.Test2<br>	at ptolemy.actor.lib.Test.fire(Test.java:268)<br>	at ptolemy.actor.process.ProcessThread._iterateActor(ProcessThread.java:339)<br>	at ptolemy.actor.process.ProcessThread.run(ProcessThread.java:213)<br>
</code></td><td>2.571</td>
</tr>
<tr valign="top" class="Error">
<td><a href="org/hlacerti/test/junit/22_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[1] /home/travis/build/icyphy/ptII/org/hlacerti/test/auto/2Classes2Values2Instances.xml (RunModel)"></a><a href="org/hlacerti/test/junit/22_JUnitTclTest.html#[1] /home/travis/build/icyphy/ptII/org/hlacerti/test/auto/2Classes2Values2Instances.xml (RunModel)">[1] /home/travis/build/icyphy/ptII/org/hlacerti/test/auto/2Classes2Values2Instances.xml (RunModel)</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.reflect.InvocationTargetException<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Exceptions occurred during wrapup:<br>ptolemy.kernel.util.IllegalActionException: Background run threw an exception<br>  in .2Classes2Values2Instances.DistributedReceiver1<br>Because:<br>CouldNotOpenFED: Module not found<br>  in .DistributedReceiver1.HlaManager<br>Because:<br>Module not found<br>ptolemy.kernel.util.IllegalActionException: Background run threw an exception<br>  in .2Classes2Values2Instances.DistributedSender1<br>Because:<br>CouldNotOpenFED: Module not found<br>  in .DistributedSender1.HlaManager<br>Because:<br>Module not found<br>
<br>  in .2Classes2Values2Instances.Director<br>Because:<br>Background run threw an exception<br>  in .2Classes2Values2Instances.DistributedReceiver1<br>Because:<br>CouldNotOpenFED: Module not found<br>  in .DistributedReceiver1.HlaManager<br>Because:<br>Module not found<br>	at ptolemy.actor.Director.wrapup(Director.java:1736)<br>	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2735)<br>	at ptolemy.actor.Manager.wrapup(Manager.java:1512)<br>	at ptolemy.actor.Manager.execute(Manager.java:407)<br>	at ptolemy.actor.Manager.run(Manager.java:1263)<br>	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Background run threw an exception<br>  in .2Classes2Values2Instances.DistributedReceiver1<br>Because:<br>CouldNotOpenFED: Module not found<br>  in .DistributedReceiver1.HlaManager<br>Because:<br>Module not found<br>	at ptolemy.actor.lib.hoc.ModelReference.wrapup(ModelReference.java:769)<br>	at ptolemy.actor.Director.wrapup(Director.java:1722)<br>Caused by: ptolemy.kernel.util.IllegalActionException: CouldNotOpenFED: Module not found<br>  in .DistributedReceiver1.HlaManager<br>Because:<br>Module not found<br>	at org.hlacerti.lib.HlaManager.initialize(HlaManager.java:671)<br>	at ptolemy.actor.CompositeActor.initialize(CompositeActor.java:912)<br>	at ptolemy.actor.Manager.initialize(Manager.java:724)<br>	at ptolemy.actor.Manager.execute(Manager.java:356)<br>	at ptolemy.actor.lib.hoc.ModelReference$1.run(ModelReference.java:626)<br>Caused by: hla.rti.CouldNotOpenFED: Module not found serial:0<br>	at certi.rti.impl.CertiRtiAmbassador.translateException(CertiRtiAmbassador.java:3832)<br>	at certi.rti.impl.CertiRtiAmbassador.processRequest(CertiRtiAmbassador.java:3773)<br>	at certi.rti.impl.CertiRtiAmbassador.createFederationExecution(CertiRtiAmbassador.java:322)<br>	at org.hlacerti.lib.HlaManager.initialize(HlaManager.java:663)<br>
</code></td><td>5.748</td>
</tr>
<tr valign="top" class="Error">
<td><a href="org/hlacerti/test/junit/22_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[2] /home/travis/build/icyphy/ptII/org/hlacerti/test/auto/2Values1Instance.xml (RunModel)"></a><a href="org/hlacerti/test/junit/22_JUnitTclTest.html#[2] /home/travis/build/icyphy/ptII/org/hlacerti/test/auto/2Values1Instance.xml (RunModel)">[2] /home/travis/build/icyphy/ptII/org/hlacerti/test/auto/2Values1Instance.xml (RunModel)</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.reflect.InvocationTargetException<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Exceptions occurred during wrapup:<br>ptolemy.kernel.util.IllegalActionException: Background run threw an exception<br>  in .2Values1Instance.DistributedReceiver1<br>Because:<br>CouldNotOpenFED: Module not found<br>  in .DistributedReceiver1.HlaManager<br>Because:<br>Module not found<br>ptolemy.kernel.util.IllegalActionException: Background run threw an exception<br>  in .2Values1Instance.DistributedSender1<br>Because:<br>CouldNotOpenFED: Module not found<br>  in .DistributedSender1.HlaManager<br>Because:<br>Module not found<br>
<br>  in .2Values1Instance.Director<br>Because:<br>Background run threw an exception<br>  in .2Values1Instance.DistributedReceiver1<br>Because:<br>CouldNotOpenFED: Module not found<br>  in .DistributedReceiver1.HlaManager<br>Because:<br>Module not found<br>	at ptolemy.actor.Director.wrapup(Director.java:1736)<br>	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2735)<br>	at ptolemy.actor.Manager.wrapup(Manager.java:1512)<br>	at ptolemy.actor.Manager.execute(Manager.java:407)<br>	at ptolemy.actor.Manager.run(Manager.java:1263)<br>	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Background run threw an exception<br>  in .2Values1Instance.DistributedReceiver1<br>Because:<br>CouldNotOpenFED: Module not found<br>  in .DistributedReceiver1.HlaManager<br>Because:<br>Module not found<br>	at ptolemy.actor.lib.hoc.ModelReference.wrapup(ModelReference.java:769)<br>	at ptolemy.actor.Director.wrapup(Director.java:1722)<br>Caused by: ptolemy.kernel.util.IllegalActionException: CouldNotOpenFED: Module not found<br>  in .DistributedReceiver1.HlaManager<br>Because:<br>Module not found<br>	at org.hlacerti.lib.HlaManager.initialize(HlaManager.java:671)<br>	at ptolemy.actor.CompositeActor.initialize(CompositeActor.java:912)<br>	at ptolemy.actor.Manager.initialize(Manager.java:724)<br>	at ptolemy.actor.Manager.execute(Manager.java:356)<br>	at ptolemy.actor.lib.hoc.ModelReference$1.run(ModelReference.java:626)<br>Caused by: hla.rti.CouldNotOpenFED: Module not found serial:0<br>	at certi.rti.impl.CertiRtiAmbassador.translateException(CertiRtiAmbassador.java:3832)<br>	at certi.rti.impl.CertiRtiAmbassador.processRequest(CertiRtiAmbassador.java:3773)<br>	at certi.rti.impl.CertiRtiAmbassador.createFederationExecution(CertiRtiAmbassador.java:322)<br>	at org.hlacerti.lib.HlaManager.initialize(HlaManager.java:663)<br>
</code></td><td>5.724</td>
</tr>
<tr valign="top" class="Error">
<td><a href="org/hlacerti/test/junit/22_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[3] /home/travis/build/icyphy/ptII/org/hlacerti/test/auto/2Values2Instances.xml (RunModel)"></a><a href="org/hlacerti/test/junit/22_JUnitTclTest.html#[3] /home/travis/build/icyphy/ptII/org/hlacerti/test/auto/2Values2Instances.xml (RunModel)">[3] /home/travis/build/icyphy/ptII/org/hlacerti/test/auto/2Values2Instances.xml (RunModel)</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.reflect.InvocationTargetException<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Exceptions occurred during wrapup:<br>ptolemy.kernel.util.IllegalActionException: Background run threw an exception<br>  in .2Values2Instances.DistributedReceiver1<br>Because:<br>CouldNotOpenFED: Module not found<br>  in .DistributedReceiver1.HlaManager<br>Because:<br>Module not found<br>ptolemy.kernel.util.IllegalActionException: Background run threw an exception<br>  in .2Values2Instances.DistributedSender1<br>Because:<br>CouldNotOpenFED: Module not found<br>  in .DistributedSender1.HlaManager<br>Because:<br>Module not found<br>
<br>  in .2Values2Instances.Director<br>Because:<br>Background run threw an exception<br>  in .2Values2Instances.DistributedReceiver1<br>Because:<br>CouldNotOpenFED: Module not found<br>  in .DistributedReceiver1.HlaManager<br>Because:<br>Module not found<br>	at ptolemy.actor.Director.wrapup(Director.java:1736)<br>	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2735)<br>	at ptolemy.actor.Manager.wrapup(Manager.java:1512)<br>	at ptolemy.actor.Manager.execute(Manager.java:407)<br>	at ptolemy.actor.Manager.run(Manager.java:1263)<br>	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Background run threw an exception<br>  in .2Values2Instances.DistributedReceiver1<br>Because:<br>CouldNotOpenFED: Module not found<br>  in .DistributedReceiver1.HlaManager<br>Because:<br>Module not found<br>	at ptolemy.actor.lib.hoc.ModelReference.wrapup(ModelReference.java:769)<br>	at ptolemy.actor.Director.wrapup(Director.java:1722)<br>Caused by: ptolemy.kernel.util.IllegalActionException: CouldNotOpenFED: Module not found<br>  in .DistributedReceiver1.HlaManager<br>Because:<br>Module not found<br>	at org.hlacerti.lib.HlaManager.initialize(HlaManager.java:671)<br>	at ptolemy.actor.CompositeActor.initialize(CompositeActor.java:912)<br>	at ptolemy.actor.Manager.initialize(Manager.java:724)<br>	at ptolemy.actor.Manager.execute(Manager.java:356)<br>	at ptolemy.actor.lib.hoc.ModelReference$1.run(ModelReference.java:626)<br>Caused by: hla.rti.CouldNotOpenFED: Module not found serial:0<br>	at certi.rti.impl.CertiRtiAmbassador.translateException(CertiRtiAmbassador.java:3832)<br>	at certi.rti.impl.CertiRtiAmbassador.processRequest(CertiRtiAmbassador.java:3773)<br>	at certi.rti.impl.CertiRtiAmbassador.createFederationExecution(CertiRtiAmbassador.java:322)<br>	at org.hlacerti.lib.HlaManager.initialize(HlaManager.java:663)<br>
</code></td><td>5.633</td>
</tr>
<tr valign="top" class="Error">
<td><a href="org/hlacerti/test/junit/22_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[4] /home/travis/build/icyphy/ptII/org/hlacerti/test/auto/3MultiDataTypes.xml (RunModel)"></a><a href="org/hlacerti/test/junit/22_JUnitTclTest.html#[4] /home/travis/build/icyphy/ptII/org/hlacerti/test/auto/3MultiDataTypes.xml (RunModel)">[4] /home/travis/build/icyphy/ptII/org/hlacerti/test/auto/3MultiDataTypes.xml (RunModel)</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.reflect.InvocationTargetException<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Execution failed.<br>  in .MultiDataTypes.Producer<br>Because:<br>CouldNotOpenFED: Module not found<br>  in .MultiDataTypesProducer.HlaManager<br>Because:<br>Module not found<br>	at ptolemy.actor.lib.hoc.ModelReference.fire(ModelReference.java:588)<br>	at ptolemy.vergil.actor.lib.VisualModelReference.fire(VisualModelReference.java:389)<br>	at ptolemy.actor.AtomicActor.iterate(AtomicActor.java:512)<br>	at ptolemy.actor.Director.fire(Director.java:360)<br>	at ptolemy.actor.CompositeActor.fire(CompositeActor.java:455)<br>	at ptolemy.actor.Manager.iterate(Manager.java:851)<br>	at ptolemy.actor.Manager.execute(Manager.java:369)<br>	at ptolemy.actor.Manager.run(Manager.java:1263)<br>	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)<br>Caused by: ptolemy.kernel.util.IllegalActionException: CouldNotOpenFED: Module not found<br>  in .MultiDataTypesProducer.HlaManager<br>Because:<br>Module not found<br>	at org.hlacerti.lib.HlaManager.initialize(HlaManager.java:671)<br>	at ptolemy.actor.CompositeActor.initialize(CompositeActor.java:912)<br>	at ptolemy.actor.Manager.initialize(Manager.java:724)<br>	at ptolemy.actor.Manager.execute(Manager.java:356)<br>	at ptolemy.actor.lib.hoc.ModelReference.fire(ModelReference.java:586)<br>Caused by: hla.rti.CouldNotOpenFED: Module not found serial:0<br>	at certi.rti.impl.CertiRtiAmbassador.translateException(CertiRtiAmbassador.java:3832)<br>	at certi.rti.impl.CertiRtiAmbassador.processRequest(CertiRtiAmbassador.java:3773)<br>	at certi.rti.impl.CertiRtiAmbassador.createFederationExecution(CertiRtiAmbassador.java:322)<br>	at org.hlacerti.lib.HlaManager.initialize(HlaManager.java:663)<br>
</code></td><td>5.197</td>
</tr>
<tr valign="top" class="Error">
<td><a href="org/hlacerti/test/junit/22_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[5] /home/travis/build/icyphy/ptII/org/hlacerti/test/auto/MultiDataTypes.xml (RunModel)"></a><a href="org/hlacerti/test/junit/22_JUnitTclTest.html#[5] /home/travis/build/icyphy/ptII/org/hlacerti/test/auto/MultiDataTypes.xml (RunModel)">[5] /home/travis/build/icyphy/ptII/org/hlacerti/test/auto/MultiDataTypes.xml (RunModel)</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.reflect.InvocationTargetException<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Exceptions occurred during wrapup:<br>ptolemy.kernel.util.IllegalActionException: Background run threw an exception<br>  in .MultiDataTypes.consumer<br>Because:<br>CouldNotOpenFED: Module not found<br>  in .MultiDataTypesConsumer.HlaManager<br>Because:<br>Module not found<br>ptolemy.kernel.util.IllegalActionException: Background run threw an exception<br>  in .MultiDataTypes.producer<br>Because:<br>CouldNotOpenFED: Module not found<br>  in .MultiDataTypesProducer.HlaManager<br>Because:<br>Module not found<br>
<br>  in .MultiDataTypes.Director<br>Because:<br>Background run threw an exception<br>  in .MultiDataTypes.consumer<br>Because:<br>CouldNotOpenFED: Module not found<br>  in .MultiDataTypesConsumer.HlaManager<br>Because:<br>Module not found<br>	at ptolemy.actor.Director.wrapup(Director.java:1736)<br>	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2735)<br>	at ptolemy.actor.Manager.wrapup(Manager.java:1512)<br>	at ptolemy.actor.Manager.execute(Manager.java:407)<br>	at ptolemy.actor.Manager.run(Manager.java:1263)<br>	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Background run threw an exception<br>  in .MultiDataTypes.consumer<br>Because:<br>CouldNotOpenFED: Module not found<br>  in .MultiDataTypesConsumer.HlaManager<br>Because:<br>Module not found<br>	at ptolemy.actor.lib.hoc.ModelReference.wrapup(ModelReference.java:769)<br>	at ptolemy.actor.Director.wrapup(Director.java:1722)<br>Caused by: ptolemy.kernel.util.IllegalActionException: CouldNotOpenFED: Module not found<br>  in .MultiDataTypesConsumer.HlaManager<br>Because:<br>Module not found<br>	at org.hlacerti.lib.HlaManager.initialize(HlaManager.java:671)<br>	at ptolemy.actor.CompositeActor.initialize(CompositeActor.java:912)<br>	at ptolemy.actor.Manager.initialize(Manager.java:724)<br>	at ptolemy.actor.Manager.execute(Manager.java:356)<br>	at ptolemy.actor.lib.hoc.ModelReference$1.run(ModelReference.java:626)<br>Caused by: hla.rti.CouldNotOpenFED: Module not found serial:0<br>	at certi.rti.impl.CertiRtiAmbassador.translateException(CertiRtiAmbassador.java:3832)<br>	at certi.rti.impl.CertiRtiAmbassador.processRequest(CertiRtiAmbassador.java:3773)<br>	at certi.rti.impl.CertiRtiAmbassador.createFederationExecution(CertiRtiAmbassador.java:322)<br>	at org.hlacerti.lib.HlaManager.initialize(HlaManager.java:663)<br>
</code></td><td>5.540</td>
</tr>
<tr valign="top" class="Error">
<td><a href="org/terraswarm/accessor/test/junit/36_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[15] /home/travis/build/icyphy/ptII/org/terraswarm/accessor/test/auto/DerivedAgain4.xml (RunModel)"></a><a href="org/terraswarm/accessor/test/junit/36_JUnitTclTest.html#[15] /home/travis/build/icyphy/ptII/org/terraswarm/accessor/test/auto/DerivedAgain4.xml (RunModel)">[15] /home/travis/build/icyphy/ptII/org/terraswarm/accessor/test/auto/DerivedAgain4.xml (RunModel)</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.reflect.InvocationTargetException<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Test fails in iteration 0.<br>Value was: 42. Should have been: 43<br>  in .DerivedAgain4.Test<br>	at ptolemy.actor.lib.Test.fire(Test.java:268)<br>	at ptolemy.domains.de.kernel.DEDirector._fire(DEDirector.java:1948)<br>	at ptolemy.domains.de.kernel.DEDirector.fire(DEDirector.java:502)<br>	at ptolemy.actor.CompositeActor.fire(CompositeActor.java:455)<br>	at ptolemy.actor.Manager.iterate(Manager.java:851)<br>	at ptolemy.actor.Manager.execute(Manager.java:369)<br>	at ptolemy.actor.Manager.run(Manager.java:1263)<br>	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)<br>
</code></td><td>1.363</td>
</tr>
<tr valign="top" class="Error">
<td><a href="ptolemy/actor/lib/jjs/modules/httpClient/test/junit/58_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[2] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/httpClient/test/auto/RESTGet.xml (RunModel)"></a><a href="ptolemy/actor/lib/jjs/modules/httpClient/test/junit/58_JUnitTclTest.html#[2] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/httpClient/test/auto/RESTGet.xml (RunModel)">[2] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/httpClient/test/auto/RESTGet.xml (RunModel)</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.reflect.InvocationTargetException<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>Caused by: java.lang.RuntimeException: REST2: The timeout period of 25000ms has been exceeded.<br>	at ptolemy.util.SimpleMessageHandler._error(SimpleMessageHandler.java:53)<br>	at ptolemy.util.MessageHandler.error(MessageHandler.java:84)<br>	at ptolemy.actor.lib.jjs.JavaScript.error(JavaScript.java:828)<br>	at ptolemy.actor.lib.jjs.RestrictedJavaScriptInterface.error(RestrictedJavaScriptInterface.java:108)<br>	at jdk.nashorn.internal.scripts.Script$Recompilation$8672$3477A$\^eval\_.error(&lt;eval&gt;:98)<br>	at jdk.nashorn.internal.scripts.Script$Recompilation$8625$11119$\^function\_.L:1#issueCommand#L:254(&lt;function&gt;:257)<br>	at jdk.nashorn.javaadapters.java.lang.Runnable.run(Unknown Source)<br>	at ptolemy.actor.lib.jjs.JavaScript.fire(JavaScript.java:1081)<br>	at ptolemy.domains.de.kernel.DEDirector._fire(DEDirector.java:1948)<br>	at ptolemy.domains.de.kernel.DEDirector.fire(DEDirector.java:502)<br>	at ptolemy.actor.CompositeActor.fire(CompositeActor.java:455)<br>	at ptolemy.actor.Manager.iterate(Manager.java:851)<br>	at ptolemy.actor.Manager.execute(Manager.java:369)<br>	at ptolemy.actor.Manager.run(Manager.java:1263)<br>	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)<br>
</code></td><td>45.830</td>
</tr>
<tr valign="top" class="Error">
<td><a href="ptolemy/actor/lib/jjs/modules/httpClient/test/junit/58_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[3] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/httpClient/test/auto/RESTGetCompleteResponseOnly.xml (RunModel)"></a><a href="ptolemy/actor/lib/jjs/modules/httpClient/test/junit/58_JUnitTclTest.html#[3] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/httpClient/test/auto/RESTGetCompleteResponseOnly.xml (RunModel)">[3] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/httpClient/test/auto/RESTGetCompleteResponseOnly.xml (RunModel)</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.reflect.InvocationTargetException<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Exceptions occurred during wrapup:<br>ptolemy.kernel.util.IllegalActionException: Failure executing the wrapup function: Error: TrainableTest2: The test produced only 1 tokens, yet the correctValues parameter was expecting 5 tokens in &lt;function&gt; at line number 399 at column number 16<br>  in .RESTGetCompleteResponseOnly.TrainableTest2<br>Because:<br>Error: TrainableTest2: The test produced only 1 tokens, yet the correctValues parameter was expecting 5 tokens in &lt;function&gt; at line number 399 at column number 16<br>
<br>  in .RESTGetCompleteResponseOnly.DE Director<br>Because:<br>Failure executing the wrapup function: Error: TrainableTest2: The test produced only 1 tokens, yet the correctValues parameter was expecting 5 tokens in &lt;function&gt; at line number 399 at column number 16<br>  in .RESTGetCompleteResponseOnly.TrainableTest2<br>Because:<br>Error: TrainableTest2: The test produced only 1 tokens, yet the correctValues parameter was expecting 5 tokens in &lt;function&gt; at line number 399 at column number 16<br>	at ptolemy.actor.Director.wrapup(Director.java:1736)<br>	at ptolemy.domains.de.kernel.DEDirector.wrapup(DEDirector.java:1526)<br>	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2735)<br>	at ptolemy.actor.Manager.wrapup(Manager.java:1512)<br>	at ptolemy.actor.Manager.execute(Manager.java:407)<br>	at ptolemy.actor.Manager.run(Manager.java:1263)<br>	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Failure executing the wrapup function: Error: TrainableTest2: The test produced only 1 tokens, yet the correctValues parameter was expecting 5 tokens in &lt;function&gt; at line number 399 at column number 16<br>  in .RESTGetCompleteResponseOnly.TrainableTest2<br>Because:<br>Error: TrainableTest2: The test produced only 1 tokens, yet the correctValues parameter was expecting 5 tokens in &lt;function&gt; at line number 399 at column number 16<br>	at ptolemy.actor.lib.jjs.JavaScript._invokeMethodInContext(JavaScript.java:2223)<br>	at ptolemy.actor.lib.jjs.JavaScript.wrapup(JavaScript.java:2118)<br>	at ptolemy.actor.Director.wrapup(Director.java:1722)<br>Caused by: javax.script.ScriptException: Error: TrainableTest2: The test produced only 1 tokens, yet the correctValues parameter was expecting 5 tokens in &lt;function&gt; at line number 399 at column number 16<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeMethod(NashornScriptEngine.java:199)<br>	at ptolemy.actor.lib.jjs.JavaScript._invokeMethodInContext(JavaScript.java:2200)<br>Caused by: &lt;function&gt;:399:16 Error: TrainableTest2: The test produced only 1 tokens, yet the correctValues parameter was expecting 5 tokens<br>	at jdk.nashorn.internal.objects.NativeError.initException(NativeError.java:137)<br>	at jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:102)<br>	at jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:106)<br>	at jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:110)<br>	at jdk.nashorn.internal.objects.NativeError.constructor(NativeError.java:129)<br>	at jdk.nashorn.internal.scripts.Script$Recompilation$11759$18524$\^function\_.L:1#wrapup(&lt;function&gt;:399)<br>	at jdk.nashorn.internal.scripts.Script$Recompilation$11757$30384$require.L:1#Accessor#wrapup(/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#401:30&lt;eval&gt;:675)<br>	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)<br>	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)<br>	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)<br>	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)<br>
</code></td><td>175.716</td>
</tr>
<tr valign="top" class="Error">
<td><a href="ptolemy/actor/lib/jjs/modules/httpClient/test/junit/58_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[4] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/httpClient/test/auto/RESTPost.xml (RunModel)"></a><a href="ptolemy/actor/lib/jjs/modules/httpClient/test/junit/58_JUnitTclTest.html#[4] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/httpClient/test/auto/RESTPost.xml (RunModel)">[4] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/httpClient/test/auto/RESTPost.xml (RunModel)</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.reflect.InvocationTargetException<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>Caused by: java.lang.RuntimeException: REST2: The timeout period of 5000ms has been exceeded.<br>	at ptolemy.util.SimpleMessageHandler._error(SimpleMessageHandler.java:53)<br>	at ptolemy.util.MessageHandler.error(MessageHandler.java:84)<br>	at ptolemy.actor.lib.jjs.JavaScript.error(JavaScript.java:828)<br>	at ptolemy.actor.lib.jjs.RestrictedJavaScriptInterface.error(RestrictedJavaScriptInterface.java:108)<br>	at jdk.nashorn.internal.scripts.Script$Recompilation$15387$3477A$\^eval\_.error(&lt;eval&gt;:98)<br>	at jdk.nashorn.internal.scripts.Script$Recompilation$15350$11119$\^function\_.L:1#issueCommand#L:254(&lt;function&gt;:257)<br>	at jdk.nashorn.javaadapters.java.lang.Runnable.run(Unknown Source)<br>	at ptolemy.actor.lib.jjs.JavaScript.fire(JavaScript.java:1081)<br>	at ptolemy.domains.de.kernel.DEDirector._fire(DEDirector.java:1948)<br>	at ptolemy.domains.de.kernel.DEDirector.fire(DEDirector.java:502)<br>	at ptolemy.actor.CompositeActor.fire(CompositeActor.java:455)<br>	at ptolemy.actor.Manager.iterate(Manager.java:851)<br>	at ptolemy.actor.Manager.execute(Manager.java:369)<br>	at ptolemy.actor.Manager.run(Manager.java:1263)<br>	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)<br>
</code></td><td>22.595</td>
</tr>
<tr valign="top" class="Error">
<td><a href="ptolemy/actor/lib/jjs/modules/httpClient/test/junit/58_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[5] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/httpClient/test/auto/RESTPostDataTypes.xml (RunModel)"></a><a href="ptolemy/actor/lib/jjs/modules/httpClient/test/junit/58_JUnitTclTest.html#[5] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/httpClient/test/auto/RESTPostDataTypes.xml (RunModel)">[5] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/httpClient/test/auto/RESTPostDataTypes.xml (RunModel)</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.reflect.InvocationTargetException<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>Caused by: java.lang.RuntimeException: REST: The timeout period of 10000ms has been exceeded.<br>	at ptolemy.util.SimpleMessageHandler._error(SimpleMessageHandler.java:53)<br>	at ptolemy.util.MessageHandler.error(MessageHandler.java:84)<br>	at ptolemy.actor.lib.jjs.JavaScript.error(JavaScript.java:828)<br>	at ptolemy.actor.lib.jjs.RestrictedJavaScriptInterface.error(RestrictedJavaScriptInterface.java:108)<br>	at jdk.nashorn.internal.scripts.Script$Recompilation$22560$3477A$\^eval\_.error(&lt;eval&gt;:98)<br>	at jdk.nashorn.internal.scripts.Script$Recompilation$22556$11119$\^function\_.L:1#issueCommand#L:254(&lt;function&gt;:257)<br>	at jdk.nashorn.javaadapters.java.lang.Runnable.run(Unknown Source)<br>	at ptolemy.actor.lib.jjs.JavaScript.fire(JavaScript.java:1081)<br>	at ptolemy.domains.de.kernel.DEDirector._fire(DEDirector.java:1948)<br>	at ptolemy.domains.de.kernel.DEDirector.fire(DEDirector.java:502)<br>	at ptolemy.actor.CompositeActor.fire(CompositeActor.java:455)<br>	at ptolemy.actor.Manager.iterate(Manager.java:851)<br>	at ptolemy.actor.Manager.execute(Manager.java:369)<br>	at ptolemy.actor.Manager.run(Manager.java:1263)<br>	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)<br>
</code></td><td>43.843</td>
</tr>
<tr valign="top" class="Error">
<td><a href="ptolemy/actor/lib/jjs/modules/httpClient/test/junit/58_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[7] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/httpClient/test/auto/RESTReceiveImage.xml (RunModel)"></a><a href="ptolemy/actor/lib/jjs/modules/httpClient/test/junit/58_JUnitTclTest.html#[7] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/httpClient/test/auto/RESTReceiveImage.xml (RunModel)">[7] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/httpClient/test/auto/RESTReceiveImage.xml (RunModel)</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.reflect.InvocationTargetException<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>Caused by: java.lang.RuntimeException: REST2: The timeout period of 5000ms has been exceeded.<br>	at ptolemy.util.SimpleMessageHandler._error(SimpleMessageHandler.java:53)<br>	at ptolemy.util.MessageHandler.error(MessageHandler.java:84)<br>	at ptolemy.actor.lib.jjs.JavaScript.error(JavaScript.java:828)<br>	at ptolemy.actor.lib.jjs.RestrictedJavaScriptInterface.error(RestrictedJavaScriptInterface.java:108)<br>	at jdk.nashorn.internal.scripts.Script$Recompilation$30958$3477A$\^eval\_.error(&lt;eval&gt;:98)<br>	at jdk.nashorn.internal.scripts.Script$Recompilation$30873$11119$\^function\_.L:1#issueCommand#L:254(&lt;function&gt;:257)<br>	at jdk.nashorn.javaadapters.java.lang.Runnable.run(Unknown Source)<br>	at ptolemy.actor.lib.jjs.JavaScript.fire(JavaScript.java:1081)<br>	at ptolemy.domains.de.kernel.DEDirector._fire(DEDirector.java:1948)<br>	at ptolemy.domains.de.kernel.DEDirector.fire(DEDirector.java:502)<br>	at ptolemy.actor.CompositeActor.fire(CompositeActor.java:455)<br>	at ptolemy.actor.Manager.iterate(Manager.java:851)<br>	at ptolemy.actor.Manager.execute(Manager.java:369)<br>	at ptolemy.actor.Manager.run(Manager.java:1263)<br>	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)<br>
</code></td><td>27.738</td>
</tr>
<tr valign="top" class="Error">
<td><a href="ptolemy/actor/lib/jjs/modules/httpServer/test/junit/59_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[0] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/httpServer/test/auto/KeyValueStoreClient.xml (RunModel)"></a><a href="ptolemy/actor/lib/jjs/modules/httpServer/test/junit/59_JUnitTclTest.html#[0] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/httpServer/test/auto/KeyValueStoreClient.xml (RunModel)">[0] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/httpServer/test/auto/KeyValueStoreClient.xml (RunModel)</a></td><td>Error</td><td>test timed out after 900000 milliseconds<br>
<br>
<code>java.lang.Exception: test timed out after 900000 milliseconds<br>	at java.lang.Object.wait(Native Method)<br>	at java.lang.Thread.join(Thread.java:1252)<br>	at java.lang.Thread.join(Thread.java:1326)<br>	at ptolemy.moml.MoMLSimpleApplication.&lt;init&gt;(MoMLSimpleApplication.java:155)<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>
</code></td><td>900.009</td>
</tr>
<tr valign="top" class="Error">
<td><a href="ptolemy/actor/lib/jjs/modules/socket/test/junit/68_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[1] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/Message2.xml (RunModel)"></a><a href="ptolemy/actor/lib/jjs/modules/socket/test/junit/68_JUnitTclTest.html#[1] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/Message2.xml (RunModel)">[1] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/Message2.xml (RunModel)</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.reflect.InvocationTargetException<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Exceptions occurred during wrapup:<br>ptolemy.kernel.util.IllegalActionException: Failure executing the wrapup function: Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>  in .Message2.TrainableTest<br>Because:<br>Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>ptolemy.kernel.util.IllegalActionException: Failure executing the wrapup function: Error: TrainableTest2: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>  in .Message2.TrainableTest2<br>Because:<br>Error: TrainableTest2: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>
<br>  in .Message2.DE Director<br>Because:<br>Failure executing the wrapup function: Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>  in .Message2.TrainableTest<br>Because:<br>Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>	at ptolemy.actor.Director.wrapup(Director.java:1736)<br>	at ptolemy.domains.de.kernel.DEDirector.wrapup(DEDirector.java:1526)<br>	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2735)<br>	at ptolemy.actor.Manager.wrapup(Manager.java:1512)<br>	at ptolemy.actor.Manager.execute(Manager.java:407)<br>	at ptolemy.actor.Manager.run(Manager.java:1263)<br>	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Failure executing the wrapup function: Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>  in .Message2.TrainableTest<br>Because:<br>Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>	at ptolemy.actor.lib.jjs.JavaScript._invokeMethodInContext(JavaScript.java:2223)<br>	at ptolemy.actor.lib.jjs.JavaScript.wrapup(JavaScript.java:2118)<br>	at ptolemy.actor.Director.wrapup(Director.java:1722)<br>Caused by: javax.script.ScriptException: Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeMethod(NashornScriptEngine.java:199)<br>	at ptolemy.actor.lib.jjs.JavaScript._invokeMethodInContext(JavaScript.java:2200)<br>Caused by: &lt;function&gt;:393:16 Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring.<br>	at jdk.nashorn.internal.objects.NativeError.initException(NativeError.java:137)<br>	at jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:102)<br>	at jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:106)<br>	at jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:110)<br>	at jdk.nashorn.internal.objects.NativeError.constructor(NativeError.java:129)<br>	at jdk.nashorn.internal.scripts.Script$Recompilation$4934$18524$\^function\_.L:1#wrapup(&lt;function&gt;:393)<br>	at jdk.nashorn.internal.scripts.Script$Recompilation$4932$30384$require.L:1#Accessor#wrapup(/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#401:30&lt;eval&gt;:675)<br>	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)<br>	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)<br>	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)<br>	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)<br>
</code></td><td>134.195</td>
</tr>
<tr valign="top" class="Error">
<td><a href="ptolemy/actor/lib/jjs/modules/socket/test/junit/68_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[6] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/Socket3.xml (RunModel)"></a><a href="ptolemy/actor/lib/jjs/modules/socket/test/junit/68_JUnitTclTest.html#[6] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/Socket3.xml (RunModel)">[6] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/Socket3.xml (RunModel)</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.reflect.InvocationTargetException<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Test fails in iteration 0.<br>Value was: "aaa". Should have been: "aa"<br>  in .Socket3.Test<br>	at ptolemy.actor.lib.Test.fire(Test.java:268)<br>	at ptolemy.domains.de.kernel.DEDirector._fire(DEDirector.java:1948)<br>	at ptolemy.domains.de.kernel.DEDirector.fire(DEDirector.java:502)<br>	at ptolemy.actor.CompositeActor.fire(CompositeActor.java:455)<br>	at ptolemy.actor.Manager.iterate(Manager.java:851)<br>	at ptolemy.actor.Manager.execute(Manager.java:369)<br>	at ptolemy.actor.Manager.run(Manager.java:1263)<br>	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)<br>
</code></td><td>10.665</td>
</tr>
<tr valign="top" class="Error">
<td><a href="ptolemy/actor/lib/jjs/modules/socket/test/junit/68_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[8] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/SocketDouble.xml (RunModel)"></a><a href="ptolemy/actor/lib/jjs/modules/socket/test/junit/68_JUnitTclTest.html#[8] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/SocketDouble.xml (RunModel)">[8] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/SocketDouble.xml (RunModel)</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.reflect.InvocationTargetException<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Exceptions occurred during wrapup:<br>ptolemy.kernel.util.IllegalActionException: The fire() method of this actor was never called. Usually, this is an error indicating that starvation is occurring.<br>  in .SocketDouble.Test<br>ptolemy.kernel.util.IllegalActionException: The fire() method of this actor was never called. Usually, this is an error indicating that starvation is occurring.<br>  in .SocketDouble.Test2<br>ptolemy.kernel.util.IllegalActionException: The fire() method of this actor was never called. Usually, this is an error indicating that starvation is occurring.<br>  in .SocketDouble.Test3<br>
<br>  in .SocketDouble.DE Director<br>Because:<br>The fire() method of this actor was never called. Usually, this is an error indicating that starvation is occurring.<br>  in .SocketDouble.Test<br>	at ptolemy.actor.Director.wrapup(Director.java:1736)<br>	at ptolemy.domains.de.kernel.DEDirector.wrapup(DEDirector.java:1526)<br>	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2735)<br>	at ptolemy.actor.Manager.wrapup(Manager.java:1512)<br>	at ptolemy.actor.Manager.execute(Manager.java:407)<br>	at ptolemy.actor.Manager.run(Manager.java:1263)<br>	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)<br>Caused by: ptolemy.kernel.util.IllegalActionException: The fire() method of this actor was never called. Usually, this is an error indicating that starvation is occurring.<br>  in .SocketDouble.Test<br>	at ptolemy.actor.lib.NonStrictTest.wrapup(NonStrictTest.java:394)<br>	at ptolemy.actor.Director.wrapup(Director.java:1722)<br>
</code></td><td>131.309</td>
</tr>
<tr valign="top" class="Error">
<td><a href="ptolemy/actor/lib/jjs/modules/socket/test/junit/68_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[9] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/SocketDoubleArray.xml (RunModel)"></a><a href="ptolemy/actor/lib/jjs/modules/socket/test/junit/68_JUnitTclTest.html#[9] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/SocketDoubleArray.xml (RunModel)">[9] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/SocketDoubleArray.xml (RunModel)</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.reflect.InvocationTargetException<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Exceptions occurred during wrapup:<br>ptolemy.kernel.util.IllegalActionException: The fire() method of this actor was never called. Usually, this is an error indicating that starvation is occurring.<br>  in .SocketDoubleArray.Test<br>ptolemy.kernel.util.IllegalActionException: The fire() method of this actor was never called. Usually, this is an error indicating that starvation is occurring.<br>  in .SocketDoubleArray.Test2<br>ptolemy.kernel.util.IllegalActionException: The fire() method of this actor was never called. Usually, this is an error indicating that starvation is occurring.<br>  in .SocketDoubleArray.Test3<br>
<br>  in .SocketDoubleArray.DE Director<br>Because:<br>The fire() method of this actor was never called. Usually, this is an error indicating that starvation is occurring.<br>  in .SocketDoubleArray.Test<br>	at ptolemy.actor.Director.wrapup(Director.java:1736)<br>	at ptolemy.domains.de.kernel.DEDirector.wrapup(DEDirector.java:1526)<br>	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2735)<br>	at ptolemy.actor.Manager.wrapup(Manager.java:1512)<br>	at ptolemy.actor.Manager.execute(Manager.java:407)<br>	at ptolemy.actor.Manager.run(Manager.java:1263)<br>	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)<br>Caused by: ptolemy.kernel.util.IllegalActionException: The fire() method of this actor was never called. Usually, this is an error indicating that starvation is occurring.<br>  in .SocketDoubleArray.Test<br>	at ptolemy.actor.lib.NonStrictTest.wrapup(NonStrictTest.java:394)<br>	at ptolemy.actor.Director.wrapup(Director.java:1722)<br>
</code></td><td>132.045</td>
</tr>
<tr valign="top" class="Error">
<td><a href="ptolemy/actor/lib/jjs/modules/socket/test/junit/68_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[11] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/SocketFloat.xml (RunModel)"></a><a href="ptolemy/actor/lib/jjs/modules/socket/test/junit/68_JUnitTclTest.html#[11] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/SocketFloat.xml (RunModel)">[11] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/SocketFloat.xml (RunModel)</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.reflect.InvocationTargetException<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>Caused by: java.lang.RuntimeException: ptolemy.kernel.util.IllegalActionException: Failed to connect: <br>Connection refused: localhost/127.0.0.1:4445<br>Connection refused<br>  in .SocketFloat.Client<br>Because:<br>Connection refused: localhost/127.0.0.1:4445<br>	at ptolemy.util.MessageHandler.error(MessageHandler.java:115)<br>	at ptolemy.actor.lib.jjs.JavaScript.error(JavaScript.java:857)<br>	at ptolemy.actor.lib.jjs.HelperBase$2.run(HelperBase.java:213)<br>	at ptolemy.actor.lib.jjs.JavaScript.fire(JavaScript.java:1050)<br>	at ptolemy.domains.de.kernel.DEDirector._fire(DEDirector.java:1948)<br>	at ptolemy.domains.de.kernel.DEDirector.fire(DEDirector.java:502)<br>	at ptolemy.actor.CompositeActor.fire(CompositeActor.java:455)<br>	at ptolemy.actor.Manager.iterate(Manager.java:851)<br>	at ptolemy.actor.Manager.execute(Manager.java:369)<br>	at ptolemy.actor.Manager.run(Manager.java:1263)<br>	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Failed to connect: <br>Connection refused: localhost/127.0.0.1:4445<br>Connection refused<br>  in .SocketFloat.Client<br>Because:<br>Connection refused: localhost/127.0.0.1:4445<br>Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:4445<br>	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)<br>	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)<br>	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:325)<br>	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)<br>	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633)<br>	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)<br>	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)<br>	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)<br>	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)<br>	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)<br>	at java.lang.Thread.run(Thread.java:748)<br>Caused by: java.net.ConnectException: Connection refused<br>
</code></td><td>20.091</td>
</tr>
<tr valign="top" class="Error">
<td><a href="ptolemy/actor/lib/jjs/modules/socket/test/junit/68_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[20] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/SocketUnsignedShort.xml (RunModel)"></a><a href="ptolemy/actor/lib/jjs/modules/socket/test/junit/68_JUnitTclTest.html#[20] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/SocketUnsignedShort.xml (RunModel)">[20] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/SocketUnsignedShort.xml (RunModel)</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.reflect.InvocationTargetException<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Exceptions occurred during wrapup:<br>ptolemy.kernel.util.IllegalActionException: The fire() method of this actor was never called. Usually, this is an error indicating that starvation is occurring.<br>  in .SocketUnsignedShort.Test<br>ptolemy.kernel.util.IllegalActionException: The fire() method of this actor was never called. Usually, this is an error indicating that starvation is occurring.<br>  in .SocketUnsignedShort.Test2<br>ptolemy.kernel.util.IllegalActionException: The fire() method of this actor was never called. Usually, this is an error indicating that starvation is occurring.<br>  in .SocketUnsignedShort.Test3<br>
<br>  in .SocketUnsignedShort.DE Director<br>Because:<br>The fire() method of this actor was never called. Usually, this is an error indicating that starvation is occurring.<br>  in .SocketUnsignedShort.Test<br>	at ptolemy.actor.Director.wrapup(Director.java:1736)<br>	at ptolemy.domains.de.kernel.DEDirector.wrapup(DEDirector.java:1526)<br>	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2735)<br>	at ptolemy.actor.Manager.wrapup(Manager.java:1512)<br>	at ptolemy.actor.Manager.execute(Manager.java:407)<br>	at ptolemy.actor.Manager.run(Manager.java:1263)<br>	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)<br>Caused by: ptolemy.kernel.util.IllegalActionException: The fire() method of this actor was never called. Usually, this is an error indicating that starvation is occurring.<br>  in .SocketUnsignedShort.Test<br>	at ptolemy.actor.lib.NonStrictTest.wrapup(NonStrictTest.java:394)<br>	at ptolemy.actor.Director.wrapup(Director.java:1722)<br>
</code></td><td>132.889</td>
</tr>
<tr valign="top" class="Error">
<td><a href="ptolemy/actor/lib/jjs/modules/socket/test/junit/68_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[22] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/TCPSocketSecureServerClient.xml (RunModel)"></a><a href="ptolemy/actor/lib/jjs/modules/socket/test/junit/68_JUnitTclTest.html#[22] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/TCPSocketSecureServerClient.xml (RunModel)">[22] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/TCPSocketSecureServerClient.xml (RunModel)</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.reflect.InvocationTargetException<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>Caused by: java.lang.RuntimeException: ptolemy.kernel.util.IllegalActionException: Failed to connect: <br>Connection refused: localhost/127.0.0.1:41119<br>Connection refused<br>  in .TCPSocketSecureServerClient.ClientB<br>Because:<br>Connection refused: localhost/127.0.0.1:41119<br>	at ptolemy.util.MessageHandler.error(MessageHandler.java:115)<br>	at ptolemy.actor.lib.jjs.JavaScript.error(JavaScript.java:857)<br>	at ptolemy.actor.lib.jjs.HelperBase$2.run(HelperBase.java:213)<br>	at ptolemy.actor.lib.jjs.JavaScript.fire(JavaScript.java:1050)<br>	at ptolemy.domains.de.kernel.DEDirector._fire(DEDirector.java:1948)<br>	at ptolemy.domains.de.kernel.DEDirector.fire(DEDirector.java:502)<br>	at ptolemy.actor.CompositeActor.fire(CompositeActor.java:455)<br>	at ptolemy.actor.Manager.iterate(Manager.java:851)<br>	at ptolemy.actor.Manager.execute(Manager.java:369)<br>	at ptolemy.actor.Manager.run(Manager.java:1263)<br>	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Failed to connect: <br>Connection refused: localhost/127.0.0.1:41119<br>Connection refused<br>  in .TCPSocketSecureServerClient.ClientB<br>Because:<br>Connection refused: localhost/127.0.0.1:41119<br>Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:41119<br>	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)<br>	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)<br>	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:325)<br>	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)<br>	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633)<br>	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)<br>	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)<br>	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)<br>	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)<br>	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)<br>	at java.lang.Thread.run(Thread.java:748)<br>Caused by: java.net.ConnectException: Connection refused<br>
</code></td><td>28.304</td>
</tr>
<tr valign="top" class="Error">
<td><a href="ptolemy/actor/lib/jjs/modules/socket/test/junit/68_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[24] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/TCPSocketUnsignedShort.xml (RunModel)"></a><a href="ptolemy/actor/lib/jjs/modules/socket/test/junit/68_JUnitTclTest.html#[24] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/TCPSocketUnsignedShort.xml (RunModel)">[24] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/socket/test/auto/TCPSocketUnsignedShort.xml (RunModel)</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.reflect.InvocationTargetException<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Exceptions occurred during wrapup:<br>ptolemy.kernel.util.IllegalActionException: Failure executing the wrapup function: Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>  in .TCPSocketUnsignedShort.TrainableTest<br>Because:<br>Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>ptolemy.kernel.util.IllegalActionException: Failure executing the wrapup function: Error: TrainableTest2: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>  in .TCPSocketUnsignedShort.TrainableTest2<br>Because:<br>Error: TrainableTest2: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>
<br>  in .TCPSocketUnsignedShort.DE Director<br>Because:<br>Failure executing the wrapup function: Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>  in .TCPSocketUnsignedShort.TrainableTest<br>Because:<br>Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>	at ptolemy.actor.Director.wrapup(Director.java:1736)<br>	at ptolemy.domains.de.kernel.DEDirector.wrapup(DEDirector.java:1526)<br>	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2735)<br>	at ptolemy.actor.Manager.wrapup(Manager.java:1512)<br>	at ptolemy.actor.Manager.execute(Manager.java:407)<br>	at ptolemy.actor.Manager.run(Manager.java:1263)<br>	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Failure executing the wrapup function: Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>  in .TCPSocketUnsignedShort.TrainableTest<br>Because:<br>Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>	at ptolemy.actor.lib.jjs.JavaScript._invokeMethodInContext(JavaScript.java:2223)<br>	at ptolemy.actor.lib.jjs.JavaScript.wrapup(JavaScript.java:2118)<br>	at ptolemy.actor.Director.wrapup(Director.java:1722)<br>Caused by: javax.script.ScriptException: Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeMethod(NashornScriptEngine.java:199)<br>	at ptolemy.actor.lib.jjs.JavaScript._invokeMethodInContext(JavaScript.java:2200)<br>Caused by: &lt;function&gt;:393:16 Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring.<br>	at jdk.nashorn.internal.objects.NativeError.initException(NativeError.java:137)<br>	at jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:102)<br>	at jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:106)<br>	at jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:110)<br>	at jdk.nashorn.internal.objects.NativeError.constructor(NativeError.java:129)<br>	at jdk.nashorn.internal.scripts.Script$Recompilation$50995$18524$\^function\_.L:1#wrapup(&lt;function&gt;:393)<br>	at jdk.nashorn.internal.scripts.Script$Recompilation$50993$30384$require.L:1#Accessor#wrapup(/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#401:30&lt;eval&gt;:675)<br>	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)<br>	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)<br>	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)<br>	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)<br>
</code></td><td>24.762</td>
</tr>
<tr valign="top" class="Error">
<td><a href="ptolemy/actor/lib/jjs/modules/udpSocket/test/junit/70_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[1] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/udpSocket/test/auto/UDPSocketSelf.xml (RunModel)"></a><a href="ptolemy/actor/lib/jjs/modules/udpSocket/test/junit/70_JUnitTclTest.html#[1] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/udpSocket/test/auto/UDPSocketSelf.xml (RunModel)">[1] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/udpSocket/test/auto/UDPSocketSelf.xml (RunModel)</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.reflect.InvocationTargetException<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Exceptions occurred during wrapup:<br>ptolemy.kernel.util.IllegalActionException: Failure executing the wrapup function: Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>  in .UDPSocketSelf.TrainableTest<br>Because:<br>Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>
<br>  in .UDPSocketSelf.DE Director<br>Because:<br>Failure executing the wrapup function: Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>  in .UDPSocketSelf.TrainableTest<br>Because:<br>Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>	at ptolemy.actor.Director.wrapup(Director.java:1736)<br>	at ptolemy.domains.de.kernel.DEDirector.wrapup(DEDirector.java:1526)<br>	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2735)<br>	at ptolemy.actor.Manager.wrapup(Manager.java:1512)<br>	at ptolemy.actor.Manager.execute(Manager.java:407)<br>	at ptolemy.actor.Manager.run(Manager.java:1263)<br>	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Failure executing the wrapup function: Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>  in .UDPSocketSelf.TrainableTest<br>Because:<br>Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>	at ptolemy.actor.lib.jjs.JavaScript._invokeMethodInContext(JavaScript.java:2223)<br>	at ptolemy.actor.lib.jjs.JavaScript.wrapup(JavaScript.java:2118)<br>	at ptolemy.actor.Director.wrapup(Director.java:1722)<br>Caused by: javax.script.ScriptException: Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeMethod(NashornScriptEngine.java:199)<br>	at ptolemy.actor.lib.jjs.JavaScript._invokeMethodInContext(JavaScript.java:2200)<br>Caused by: &lt;function&gt;:393:16 Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring.<br>	at jdk.nashorn.internal.objects.NativeError.initException(NativeError.java:137)<br>	at jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:102)<br>	at jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:106)<br>	at jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:110)<br>	at jdk.nashorn.internal.objects.NativeError.constructor(NativeError.java:129)<br>	at jdk.nashorn.internal.scripts.Script$Recompilation$2958$18524$\^function\_.L:1#wrapup(&lt;function&gt;:393)<br>	at jdk.nashorn.internal.scripts.Script$Recompilation$2956$30384$require.L:1#Accessor#wrapup(/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#401:30&lt;eval&gt;:675)<br>	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)<br>	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)<br>	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)<br>	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)<br>
</code></td><td>135.379</td>
</tr>
<tr valign="top" class="Error">
<td><a href="ptolemy/actor/lib/jjs/modules/udpSocket/test/junit/70_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[2] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/udpSocket/test/auto/UDPSocketString.xml (RunModel)"></a><a href="ptolemy/actor/lib/jjs/modules/udpSocket/test/junit/70_JUnitTclTest.html#[2] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/udpSocket/test/auto/UDPSocketString.xml (RunModel)">[2] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/udpSocket/test/auto/UDPSocketString.xml (RunModel)</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.reflect.InvocationTargetException<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Exceptions occurred during wrapup:<br>ptolemy.kernel.util.IllegalActionException: The fire() method of this actor was never called. Usually, this is an error indicating that starvation is occurring.<br>  in .UDPSocketString.Test<br>
<br>  in .UDPSocketString.DE Director<br>Because:<br>The fire() method of this actor was never called. Usually, this is an error indicating that starvation is occurring.<br>  in .UDPSocketString.Test<br>	at ptolemy.actor.Director.wrapup(Director.java:1736)<br>	at ptolemy.domains.de.kernel.DEDirector.wrapup(DEDirector.java:1526)<br>	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2735)<br>	at ptolemy.actor.Manager.wrapup(Manager.java:1512)<br>	at ptolemy.actor.Manager.execute(Manager.java:407)<br>	at ptolemy.actor.Manager.run(Manager.java:1263)<br>	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)<br>Caused by: ptolemy.kernel.util.IllegalActionException: The fire() method of this actor was never called. Usually, this is an error indicating that starvation is occurring.<br>  in .UDPSocketString.Test<br>	at ptolemy.actor.lib.NonStrictTest.wrapup(NonStrictTest.java:394)<br>	at ptolemy.actor.Director.wrapup(Director.java:1722)<br>
</code></td><td>127.905</td>
</tr>
<tr valign="top" class="Error">
<td><a href="ptolemy/actor/lib/jjs/modules/webSocket/test/junit/71_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[1] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/webSocket/test/auto/FullDuplex2.xml (RunModel)"></a><a href="ptolemy/actor/lib/jjs/modules/webSocket/test/junit/71_JUnitTclTest.html#[1] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/webSocket/test/auto/FullDuplex2.xml (RunModel)">[1] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/webSocket/test/auto/FullDuplex2.xml (RunModel)</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.reflect.InvocationTargetException<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Exceptions occurred during wrapup:<br>ptolemy.kernel.util.IllegalActionException: Failure executing the wrapup function: Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>  in .FullDuplex2.TrainableTest<br>Because:<br>Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>ptolemy.kernel.util.IllegalActionException: Failure executing the wrapup function: Error: TrainableTest2: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>  in .FullDuplex2.TrainableTest2<br>Because:<br>Error: TrainableTest2: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>
<br>  in .FullDuplex2.DE Director<br>Because:<br>Failure executing the wrapup function: Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>  in .FullDuplex2.TrainableTest<br>Because:<br>Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>	at ptolemy.actor.Director.wrapup(Director.java:1736)<br>	at ptolemy.domains.de.kernel.DEDirector.wrapup(DEDirector.java:1526)<br>	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2735)<br>	at ptolemy.actor.Manager.wrapup(Manager.java:1512)<br>	at ptolemy.actor.Manager.execute(Manager.java:407)<br>	at ptolemy.actor.Manager.run(Manager.java:1263)<br>	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Failure executing the wrapup function: Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>  in .FullDuplex2.TrainableTest<br>Because:<br>Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>	at ptolemy.actor.lib.jjs.JavaScript._invokeMethodInContext(JavaScript.java:2223)<br>	at ptolemy.actor.lib.jjs.JavaScript.wrapup(JavaScript.java:2118)<br>	at ptolemy.actor.Director.wrapup(Director.java:1722)<br>Caused by: javax.script.ScriptException: Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeMethod(NashornScriptEngine.java:199)<br>	at ptolemy.actor.lib.jjs.JavaScript._invokeMethodInContext(JavaScript.java:2200)<br>Caused by: &lt;function&gt;:393:16 Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring.<br>	at jdk.nashorn.internal.objects.NativeError.initException(NativeError.java:137)<br>	at jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:102)<br>	at jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:106)<br>	at jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:110)<br>	at jdk.nashorn.internal.objects.NativeError.constructor(NativeError.java:129)<br>	at jdk.nashorn.internal.scripts.Script$Recompilation$3014$18524$\^function\_.L:1#wrapup(&lt;function&gt;:393)<br>	at jdk.nashorn.internal.scripts.Script$Recompilation$3012$30384$require.L:1#Accessor#wrapup(/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#401:30&lt;eval&gt;:675)<br>	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)<br>	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)<br>	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)<br>	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)<br>
</code></td><td>514.052</td>
</tr>
<tr valign="top" class="Error">
<td><a href="ptolemy/actor/lib/jjs/modules/webSocket/test/junit/71_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[2] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/webSocket/test/auto/WebSocketClient2JS.xml (RunModel)"></a><a href="ptolemy/actor/lib/jjs/modules/webSocket/test/junit/71_JUnitTclTest.html#[2] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/webSocket/test/auto/WebSocketClient2JS.xml (RunModel)">[2] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/webSocket/test/auto/WebSocketClient2JS.xml (RunModel)</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.reflect.InvocationTargetException<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Exceptions occurred during wrapup:<br>ptolemy.kernel.util.IllegalActionException: Failure executing the wrapup function: Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>  in .WebSocketClient2JS.TrainableTest<br>Because:<br>Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>
<br>  in .WebSocketClient2JS.DE Director<br>Because:<br>Failure executing the wrapup function: Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>  in .WebSocketClient2JS.TrainableTest<br>Because:<br>Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>	at ptolemy.actor.Director.wrapup(Director.java:1736)<br>	at ptolemy.domains.de.kernel.DEDirector.wrapup(DEDirector.java:1526)<br>	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2735)<br>	at ptolemy.actor.Manager.wrapup(Manager.java:1512)<br>	at ptolemy.actor.Manager.execute(Manager.java:407)<br>	at ptolemy.actor.Manager.run(Manager.java:1263)<br>	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Failure executing the wrapup function: Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>  in .WebSocketClient2JS.TrainableTest<br>Because:<br>Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>	at ptolemy.actor.lib.jjs.JavaScript._invokeMethodInContext(JavaScript.java:2223)<br>	at ptolemy.actor.lib.jjs.JavaScript.wrapup(JavaScript.java:2118)<br>	at ptolemy.actor.Director.wrapup(Director.java:1722)<br>Caused by: javax.script.ScriptException: Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeMethod(NashornScriptEngine.java:199)<br>	at ptolemy.actor.lib.jjs.JavaScript._invokeMethodInContext(JavaScript.java:2200)<br>Caused by: &lt;function&gt;:393:16 Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring.<br>	at jdk.nashorn.internal.objects.NativeError.initException(NativeError.java:137)<br>	at jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:102)<br>	at jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:106)<br>	at jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:110)<br>	at jdk.nashorn.internal.objects.NativeError.constructor(NativeError.java:129)<br>	at jdk.nashorn.internal.scripts.Script$Recompilation$4697$18524$\^function\_.L:1#wrapup(&lt;function&gt;:393)<br>	at jdk.nashorn.internal.scripts.Script$Recompilation$4695$30384$require.L:1#Accessor#wrapup(/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#401:30&lt;eval&gt;:675)<br>	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)<br>	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)<br>	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)<br>	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)<br>
</code></td><td>133.757</td>
</tr>
<tr valign="top" class="Error">
<td><a href="ptolemy/actor/lib/jjs/modules/webSocket/test/junit/71_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[3] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/webSocket/test/auto/WebSocketClient3JS.xml (RunModel)"></a><a href="ptolemy/actor/lib/jjs/modules/webSocket/test/junit/71_JUnitTclTest.html#[3] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/webSocket/test/auto/WebSocketClient3JS.xml (RunModel)">[3] /home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/modules/webSocket/test/auto/WebSocketClient3JS.xml (RunModel)</a></td><td>Error</td><td>N/A<br>
<br>
<code>java.lang.reflect.InvocationTargetException<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br>	at ptolemy.util.test.junit.AutoTests.RunModel(AutoTests.java:185)<br>	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Exceptions occurred during wrapup:<br>ptolemy.kernel.util.IllegalActionException: Failure executing the wrapup function: Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>  in .WebSocketClient3JS.TrainableTest<br>Because:<br>Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>
<br>  in .WebSocketClient3JS.DE Director<br>Because:<br>Failure executing the wrapup function: Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>  in .WebSocketClient3JS.TrainableTest<br>Because:<br>Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>	at ptolemy.actor.Director.wrapup(Director.java:1736)<br>	at ptolemy.domains.de.kernel.DEDirector.wrapup(DEDirector.java:1526)<br>	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2735)<br>	at ptolemy.actor.Manager.wrapup(Manager.java:1512)<br>	at ptolemy.actor.Manager.execute(Manager.java:407)<br>	at ptolemy.actor.Manager.run(Manager.java:1263)<br>	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)<br>Caused by: ptolemy.kernel.util.IllegalActionException: Failure executing the wrapup function: Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>  in .WebSocketClient3JS.TrainableTest<br>Because:<br>Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>	at ptolemy.actor.lib.jjs.JavaScript._invokeMethodInContext(JavaScript.java:2223)<br>	at ptolemy.actor.lib.jjs.JavaScript.wrapup(JavaScript.java:2118)<br>	at ptolemy.actor.Director.wrapup(Director.java:1722)<br>Caused by: javax.script.ScriptException: Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring. in &lt;function&gt; at line number 393 at column number 16<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeMethod(NashornScriptEngine.java:199)<br>	at ptolemy.actor.lib.jjs.JavaScript._invokeMethodInContext(JavaScript.java:2200)<br>Caused by: &lt;function&gt;:393:16 Error: TrainableTest: The input handler of this accessor was never invoked. Usually, this is an error indicating that starvation is occurring.<br>	at jdk.nashorn.internal.objects.NativeError.initException(NativeError.java:137)<br>	at jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:102)<br>	at jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:106)<br>	at jdk.nashorn.internal.objects.NativeError.&lt;init&gt;(NativeError.java:110)<br>	at jdk.nashorn.internal.objects.NativeError.constructor(NativeError.java:129)<br>	at jdk.nashorn.internal.scripts.Script$Recompilation$6368$18524$\^function\_.L:1#wrapup(&lt;function&gt;:393)<br>	at jdk.nashorn.internal.scripts.Script$Recompilation$6366$30384$require.L:1#Accessor#wrapup(/home/travis/build/icyphy/ptII/ptolemy/actor/lib/jjs/external/require.js#401:30&lt;eval&gt;:675)<br>	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)<br>	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)<br>	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)<br>	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)<br>	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)<br>
</code></td><td>172.600</td>
</tr>
<tr valign="top" class="Error">
<td><a href="ptolemy/cg/lib/testKnownFailed/test/junit/106_JUnitTclTest.html">JUnitTclTest</a></td><td><a name="[0] /home/travis/build/icyphy/ptII/ptolemy/cg/lib/testKnownFailed/test/auto/knownFailedTests/ScaleC.xml (RunModel)"></a><a href="ptolemy/cg/lib/testKnownFailed/test/junit/106_JUnitTclTest.html#[0] /home/travis/build/icyphy/ptII/ptolemy/cg/lib/testKnownFailed/test/auto/knownFailedTests/ScaleC.xml (RunModel)">[0] /home/travis/build/icyphy/ptII/ptolemy/cg/lib/testKnownFailed/test/auto/knownFailedTests/ScaleC.xml (RunModel)</a></td><td>Error</td><td>Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.<br>
<br>
<code>junit.framework.AssertionFailedError: Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.<br>
</code></td><td>0.000</td>
</tr>
</table>
</body>
</html>
